//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_supplier
    {
        public int branch_id { get; set; }
        public string supplier_name { get; set; }
        public string supply_type { get; set; }
    
        public virtual branch branch { get; set; }
    }
}
