//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.branch_supplier = new HashSet<branch_supplier>();
            this.clients = new HashSet<client>();
            this.employees = new HashSet<employee>();
        }
    
        public int branch_id { get; set; }
        public string branch_name { get; set; }
        public Nullable<int> mgr_id { get; set; }
        public Nullable<System.DateTime> mgr_start_date { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<branch_supplier> branch_supplier { get; set; }
        public virtual ICollection<client> clients { get; set; }
        public virtual ICollection<employee> employees { get; set; }
    }
}
