//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.work_with = new HashSet<work_with>();
        }
    
        public int client_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string client_name { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual ICollection<work_with> work_with { get; set; }
    }
}
