//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.branches = new HashSet<branch>();
            this.employee1 = new HashSet<employee>();
            this.work_with = new HashSet<work_with>();
        }
    
        public int emp_id { get; set; }
        public string firest_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birth_day { get; set; }
        public string sex { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> super_id { get; set; }
        public Nullable<int> branch_id { get; set; }
    
        public virtual ICollection<branch> branches { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual ICollection<work_with> work_with { get; set; }
    }
}
