//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    public interface Iuser1
    {
        int address { get; set; }
        string name { get; set; }
        int passward { get; set; }
        int? phone_number { get; set; }
    }
}