         //------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class companyEntities : DbContext
    {
        public companyEntities()
            : base("name=companyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<branch> branches { get; set; }
        public DbSet<branch_supplier> branch_supplier { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<work_with> work_with { get; set; }
        public DbSet<user> users { get; set; }
    }
}
