//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_with
    {
        public int emp_id { get; set; }
        public int client_id { get; set; }
        public Nullable<int> total_sale { get; set; }
    
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
    }
}
